language: go

go:
  - 1.9

install:
  - go get -t github.com/NebulousLabs/writeaheadlog
  - go get -u github.com/golang/lint/golint
  - test -z "$(go fmt)"
  - test -z "$(golint)"

script: go vet && go test -v -short -race && go test -v

branches:
  only:
    - master

notifications:
  email: false
