version: "{build}"

platform: x64

clone_folder: c:\GOPATH\src\github.com\NebulousLabs\wal

shallow_clone: true

environment:
  GOPATH: c:\GOPATH

branches:
  only:
    - master

install:
  - go version
  - go env
  - go get -d -t ./...

build_script:
  - go test -v -short -race && go test -v
